#spring config
spring:
  application:
    name: eureka-server
#eureka config
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    healthcheck:
      enabled: true
